typography_spectrum: 0.4016566553618759
color:
  brandStrength: 0.8667293391190469
  lightness: 0.9725218075327575
  saturation: 0.7545820337254554
  rhythmicContrast: 0.30234033591113985
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.20875878282822669
name: Shiftd Hockey
navigation:
  - name: What We Do
    url: 'http://shiftd.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca27c9cc-37a0-407f-813d-458340c9747c.png
title: Shiftd Hockey
description: Empower Through Knowledge
