typography_spectrum: 0.46638740017078817
color:
  brandStrength: 0.003929134923964739
  lightness: 0.8331252357456833
  saturation: 0.05774485250003636
  rhythmicContrast: 0.26802373374812305
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.30678534507751465
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f3e184ff-91bb-4e21-ba59-d9b949c44724.png
name: Shiftd Hockey
navigation:
  - name: What We Do
    url: 'http://shiftd.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca27c9cc-37a0-407f-813d-458340c9747c.png
title: Shiftd Hockey
description: Empower Through Knowledge
