typography_spectrum: 0.9628791173454374
color:
  brandStrength: 0.7002772784326226
  lightness: 0.16196032264269888
  saturation: 0.27353059663437307
  rhythmicContrast: 0.7733870272058994
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.20875878282822669
name: Shiftd Hockey
navigation:
  - name: What We Do
    url: 'http://shiftd.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca27c9cc-37a0-407f-813d-458340c9747c.png
title: Shiftd Hockey
description: Empower Through Knowledge
